language: cpp
sudo: required
matrix:
    include:
    - name: "macOS Build"
      os: osx
      compiler: clang
      osx_image: xcode11.3
      script:
        - bash scripts/build.macos.release.sh
      before_deploy:
        - bash scripts/build.macos.clients.sh
        - mv base stairspeedtest
        - tar czf stairspeedtest_reborn_darwin64.tar.gz stairspeedtest
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: "stairspeedtest_reborn_darwin64.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - name: "Linux x86 Build"
      services: docker
      script:
        - docker run -v $TRAVIS_BUILD_DIR:/root/workdir -e TRAVIS_BRANCH -e TRAVIS_TAG multiarch/alpine:x86-latest-stable /bin/sh -c "apk add bash git && cd /root/workdir && bash scripts/build.alpine.release.sh"
      before_deploy:
        - tar czf stairspeedtest_reborn_linux32.tar.gz stairspeedtest
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: "stairspeedtest_reborn_linux32.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - name: "Linux x86_64 Build"
      services: docker
      script:
        - docker run -v $TRAVIS_BUILD_DIR:/root/workdir -e TRAVIS_BRANCH -e TRAVIS_TAG multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git && cd /root/workdir && bash scripts/build.alpine.release.sh"
      before_deploy:
        - tar czf stairspeedtest_reborn_linux64.tar.gz stairspeedtest
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: "stairspeedtest_reborn_linux64.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - name: "Linux ARMHF Build"
      services: docker
      arch: arm64
      script:
        - docker run -v $TRAVIS_BUILD_DIR:/root/workdir -e TRAVIS_BRANCH -e TRAVIS_TAG multiarch/alpine:armhf-latest-stable /bin/sh -c "apk add bash git && cd /root/workdir && bash scripts/build.alpine.release.sh"
      before_deploy:
        - tar czf stairspeedtest_reborn_armhf.tar.gz stairspeedtest
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: "stairspeedtest_reborn_armhf.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - name: "Linux ARM64 Build"
      arch: arm64
      services: docker
      script:
        - docker run -v $TRAVIS_BUILD_DIR:/root/workdir -e TRAVIS_BRANCH -e TRAVIS_TAG multiarch/alpine:aarch64-latest-stable /bin/sh -c "apk add bash git && cd /root/workdir && bash scripts/build.alpine.release.sh"
      before_deploy:
        - tar czf stairspeedtest_reborn_arm64.tar.gz stairspeedtest
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        file: "stairspeedtest_reborn_arm64.tar.gz"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - name: "Windows x86_64 Build"
      os: windows
      before_install:
      - |-
         [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
         choco uninstall -y mingw
         choco upgrade --no-progress -y msys2
         export msys2='cmd //C RefreshEnv.cmd '
         export msys2+='& set MSYS=winsymlinks:nativestrict '
         export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
         export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
         export msys2+=" -msys2 -c "\"\$@"\" --"
         $msys2 pacman --sync --noconfirm --needed base-devel git mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-libevent mingw-w64-x86_64-pcre2 mingw-w64-x86_64-freetype mingw-w64-x86_64-libpng mingw-w64-x86_64-bzip2 mingw-w64-x86_64-openssl mingw-w64-x86_64-mbedtls mingw-w64-x86_64-libsodium mingw-w64-x86_64-c-ares mingw-w64-x86_64-boost mingw-w64-x86_64-libmariadbclient unzip
         taskkill //IM gpg-agent.exe //F
         export PATH=/C/tools/msys64/mingw64/bin:$PATH
         export MAKE=make
      install:
      - |-
        [[ -d ~/maindeps-64/ ]] && mv ~/maindeps-64 ~/maindeps
        [[ -d ~/clients-64/ ]] && mv ~/clients-64 ~/clients
        $mingw64 bash scripts/build.windows.maindeps.sh
        $mingw64 bash scripts/build.windows.clients.sh
      before_cache:
      - |-
        mv ~/maindeps ~/maindeps-64
        mv ~/clients ~/clients-64
        $msys2 pacman --sync --clean --noconfirm
      cache:
        directories:
        - $HOME/AppData/Local/Temp/chocolatey
        - ~/maindeps-32
        - ~/clients-32
        - ~/maindeps-64
        - ~/clients-64
      script:
        - $mingw64 bash scripts/build.windows.release.sh
      before_deploy:
        - mv ~/clients-64/built/websocketd.exe base/tools/gui/
        - mv ~/clients-64/built base/tools/clients
        - mv base stairspeedtest
        - 7z a stairspeedtest_reborn_win64.7z stairspeedtest/
      deploy:
        provider: releases
        token: "$GITHUB_OAUTH_TOKEN"
        file: "stairspeedtest_reborn_win64.7z"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - name: "Windows x86 Build"
      os: windows
      before_install:
      - |-
         [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
         choco uninstall -y mingw
         choco upgrade --no-progress -y msys2
         export msys2='cmd //C RefreshEnv.cmd '
         export msys2+='& set MSYS=winsymlinks:nativestrict '
         export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
         export mingw32="$msys2 -mingw32 -full-path -here -c "\"\$@"\" --"
         export msys2+=" -msys2 -c "\"\$@"\" --"
         $msys2 pacman --sync --noconfirm --needed base-devel git mingw-w64-i686-gcc mingw-w64-i686-cmake mingw-w64-i686-libevent mingw-w64-i686-pcre2 mingw-w64-i686-freetype mingw-w64-i686-libpng mingw-w64-i686-bzip2 mingw-w64-i686-openssl mingw-w64-i686-mbedtls mingw-w64-i686-libsodium mingw-w64-i686-c-ares mingw-w64-i686-boost mingw-w64-i686-libmariadbclient unzip
         taskkill //IM gpg-agent.exe //F
         export PATH=/C/tools/msys64/mingw64/bin:$PATH
         export MAKE=make
      install:
      - |-
        [[ -d ~/maindeps-32/ ]] && mv ~/maindeps-32 ~/maindeps
        [[ -d ~/clients-32/ ]] && mv ~/clients-32 ~/clients
        $mingw32 bash scripts/build.windows.clients.sh
        $mingw32 bash scripts/build.windows.maindeps.sh
      before_cache:
      - |-
        mv ~/maindeps ~/maindeps-32
        mv ~/clients ~/clients-32
        $msys2 pacman --sync --clean --noconfirm
      cache:
        directories:
        - $HOME/AppData/Local/Temp/chocolatey
        - ~/maindeps-32
        - ~/clients-32
        - ~/maindeps-64
        - ~/clients-64
      script:
        - $mingw32 bash scripts/build.windows.release.sh
      before_deploy:
        - mv ~/clients-32/built/websocketd.exe base/tools/gui/
        - mv ~/clients-32/built base/tools/clients
        - mv base stairspeedtest
        - 7z a stairspeedtest_reborn_win32.7z stairspeedtest/
      deploy:
        provider: releases
        token: "$GITHUB_OAUTH_TOKEN"
        file: "stairspeedtest_reborn_win32.7z"
        skip_cleanup: true
        draft: true
        on:
          tags: true
